version: '2.1' #We use this version due to limitations in depends_on

services:
  r2dbc-postgres:
    image: postgres:11.4-alpine
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: books
    ports:
      - 5430:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d books"]
      interval: 5s
      timeout: 31s
      retries: 6